employee <- c('John Doe','Peter Gynn','Jolie Hope')
salary <- c(21000, 23400, 26800)
startdate <- as.Date(c('2010-11-1','2008-3-25','2007-3-14'))

employ.data <- data.frame(employee, salary, startdate)
str(employ.data) 
colnames(employ.data) = c("a","b","c")
colnames(employ.data) = c("employee","salary","startdate")
Lab1<-read.csv(file="Lab1.csv", header=TRUE)
Lab1_false<-read.csv(file="Lab1.csv", header=FALSE)
summary(Lab1$AGE) 
table(Lab1$Gender) 
table.gender <- table(Lab1$Gender)
prop.table(table.gender)
table(Lab1$EDUC, Lab1$Gender) 
ftable(Lab1$EDUC, Lab1$Gender, Lab1$Job.class) 
hist(Lab1$AGE) 
boxplot(Lab1$AGE) 
boxplot(Lab1$AGE~Lab1$Gender)
plot(Lab1$EARN, Lab1$AGE) 
Lab1$EARN_1000 = Lab1$EARN/1000 
plot(Lab1$EARN_1000, Lab1$AGE)
